### ISSUE TITLE
Feature request: Exclude pinned tabs

### ISSUE THREAD

**Issue by Simonlp95** [BigBrain-Industries/recent-tabs#2]
Greetings,

I really enjoy this simple extension and want to keep using it. The only feature that is missing is i want to have my pinned tabs stay in place and not move around when switching between them. 
Is it possible to add a toggle for excluding pinned tabs? If so, I would be a happy man 🥇

**Comment by BigBrain-Industries** [comment]
I see this issue in Chrome but not Firefox. Are you asking about Chrome?

**Comment by BigBrain-Industries** [comment]
this is fixed in the latest version on Chrome.
